### ISSUE TITLE
`:=` for the IO slides?

### ISSUE THREAD

**Issue by rsmith013** [ncasuk/ncas-isc#130]
Replace the declarations of variables with the walrus

**Comment by alaniwi** [comment]
I think it would need an additional slide with the existing version and the walrus version side by side, so that it can be explained what it does and how it helps having the same line of code in two places. 

e.g.

```
data = reader.read(64)
while data != '':
    .......
    data = reader.read(64)
```
and:
```
while (data := reader.read(64)) != '':
    .......
```

**Comment by alaniwi** [comment]
Another alternative:

```
while True:
    data = reader.read(64)
    if data == '':
        break
    .....
```
