### ISSUE TITLE
Refactor ISC github

### ISSUE THREAD

**Issue by alaniwi** [ncasuk/ncas-isc#164]
- new branch: isc-2023
- create:
  - python-intro
  - python-data
- within each of them:
  - notebooks
  - solutions
  - example_data
  - example_code
  - slides
- within "python-intro/slides/":
  - include all of: python/presentations/learning_python/*.*
- within "python-data/slides/":
  - include all files from the following directories (without sub-directories):
    - python/presentations/data_tools/
    - python/presentations/handling_arrays/
    - python/presentations/read_write_data/
    - python/presentations/visualisation/
  
- NOTE: we can destroy:
  - presentations/logging-data-from-serial-ports
  
- review, merge into main, and then create a new release

**Comment by agstephens** [comment]
Hi @alaniwi, Is this ready for review? Thanks
