### ISSUE TITLE
Broken links in Python Working with Data slides

### ISSUE THREAD

**Issue by danny-lloyd** [ncasuk/ncas-isc#178]
Three links on the last page of the PDF `python-data/slides/03_text_formats_ceda.pdf` are broken:

- http://cedadocs.badc.rl.ac.uk/73/3/G-and-H-June-1998.html
- http://badc.nerc.ac.uk/help/formats/NASA-Ames/
- http://www.ceda.ac.uk/help/users-guide/file-formats/badc-csv/

In the same folder, the links towards the end of the PDF `08_cf_metadata_conventions.pdf` are not HTTPS and/or broken:

- http://puma.nerc.ac.uk/cgi-bin/cf-checker.pl
- http://cfconventions.org/
- http://mailman.cgd.ucar.edu/mailman/listinfo/cf-metadata

In `09_cfchecker.pdf`:

- https://ceda-wps-ui.ceda.ac.uk/processes/execute?wps=compliance_checker&process=CFCheck
- The second slide about a lack of Python 3 support is out-of-date

In `10_read_netcdf_python.pdf` not HTTPS:

- http://unidata.github.io/netcdf4-python/

In `11_create_netcdf_python.pdf` not HTTPS:

- http://unidata.github.io/netcdf4-python/

In `12_python_and_other_formats.pdf` not HTTPS:

- http://planetpython.org/rss20.xml (in the first code sample)

In `13_ncview_ncbrowse.pdf`:

- These screenshots look pretty old, does the program still work?
- http://meteora.ucsd.edu/~pierce/ncview_home_page.html
- https://www.nodc.noaa.gov/woce/woce_v3/wocedata_1/utils/n (redirects to https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.nodc:NODC-WOCE-GDR)

**Comment by nf679** [comment]
Yep the links are broken and the screenshots look old but I'm archiving the slides now as we're swapping to SC format. I've merged the PR to change links to HTTPS though!
