### ISSUE TITLE
update a solution for python 3

### ISSUE THREAD

**Issue by alaniwi** [ncasuk/ncas-isc#23]
solution to exercise 3 (lists and slicing), question 2, change `range(...)` to `list(range(...))`

**Comment by alaniwi** [comment]
@tommygod3

**Comment by tommygod3** [comment]
I'll fix this on my fork and make a pull request early next week

**Comment by tommygod3** [comment]
This has been fixed on my fork and will be a pull request to master today

**Comment by agstephens** [comment]
Fixed in PR 31.
