### ISSUE TITLE
Cover break and continue in control flow

### ISSUE THREAD

**Issue by alaniwi** [ncasuk/ncas-isc#24]

**Comment by alaniwi** [comment]
In exercise solution with:

```
line = reader.readline()
while line:
    print(line)
    line = reader.readline()
```

if `break` is covered, can rewrite as:
```
while True:
    line = reader.readline()
    if not line:
        break
    print(line)
```

to avoid repeating the `line = reader.readline()` both inside and outside the loop.

The corresponding section of the teaching materials would need to be changed accordingly.

**Comment by tommygod3** [comment]
https://github.com/tommygod3/ncas-isc/issues/26

**Comment by agstephens** [comment]
Fixed in PR 31.
