### ISSUE TITLE
pdb and single-character variables

### ISSUE THREAD

**Issue by alaniwi** [ncasuk/ncas-isc#28]
The example has
```
(Pdb) x
```
to show the value of `x`. This happens to work, but many other single characters are pdb commands.  It would be worth mentioning that if a pdb command exists then this will be done in preference to printing out variable contents, so that if you do not get the expected behaviour then either use a longer variable name or else do an explicit `print(...)`

**Comment by agstephens** [comment]
Yes, just update slides to use `print(...)` rather than just variable.

**Comment by agstephens** [comment]
Fixed in PR 31.
