### ISSUE TITLE
How will we teach git/github in the online course?

### ISSUE THREAD

**Issue by agstephens** [ncasuk/ncas-isc#51]
When we teach the Python section of the ISC remotely, we will not be working in a Linux shell environment. This means that teaching the command-line `git` interface is not going to be as straightforward. There are a few ways we could approach this:

**Option 1:** Remove the teaching of git/github from the course completely

**Option 2:** Include more demos of using git/github - but without _real-world_ practice for the students

**Option 3:** Frequently _switch_ to the Linux environment (using the JASMIN Training Accounts, on the `sci` servers) - and encourage users to create push their notebooks to github. 

I think it is logical to go for **Option 3**, with the following:
- add in some regular _git-stops_, between teaching the Python, where we demo the git/github interactions and hope that they copy us
- add in a Slack channel "#git-help" - and provide 1-to-1 support as required

@spepler @rsmith013 @japamment @alaniwi - what do you think?

**Comment by rsmith013** [comment]
doing option 3 will also force them to `ssh` more often. This might mean we have more `ssh` issues to solve as well, but at least they'll get the practice.

**Comment by agstephens** [comment]
Expanding on to manage this in each training account (SSH):
- put a read-only `export` of the `ncas-isc` content within each `$HOME` directory
- copy all the test data in locations relative to the `$HOME` directory
- instruct the user to:
  - create a github account
  - create a new repo (on github)
  - clone their repo to their `$HOME` dir (`~/my-isc-work`)
  - copy the exercise notebooks to their own repo
  - tell them to do their work in _that_ repo

**Comment by agstephens** [comment]
Need to think about authentication!

**Comment by lecjlg** [comment]
@agstephens it might be worth outlining there are two ways to authenticate with Git hub, passwords and using keys. Are you covering keys earlier in the course? It might be another opportunity to sell the benefits of becoming familiar with keys ?

**Comment by agstephens** [comment]
> @agstephens it might be worth outlining there are two ways to authenticate with Git hub, passwords and using keys. Are you covering keys earlier in the course? It might be another opportunity to sell the benefits of becoming familiar with keys ?

@lecjlg: Github has stopped allowing writes to repos using the username/password, you have to generate a personal access token now (https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) - so things are more secure than they were. I agree that we should explain that they can use SSH keys or access tokens. 👍

**Comment by agstephens** [comment]
This is all resolved now in the `.../version_control/` directory in the repo, we will:
1. give the presentation
2. work them through the exercise.
