### ISSUE TITLE
git clone failing with `early EOF` 

### ISSUE THREAD

**Issue by rsmith013** [ncasuk/ncas-isc#55]
I have spent the last hour trying to clone the repo. It was failing with an EOF error
```
fatal: the remote end hung up unexpectedly MiB | 6.48 MiB/s  
fatal: early EOF
fatal: index-pack failed
```
The workaround I found, meant that I couldn’t access any of the branches but have found a workaround around the workaround.
Posting here in case others have the same issue. The solution seemed to be:
1. `git clone --depth 1 https://github.com/ncasuk/ncas-isc.git`  Get a shallow clone
2. `git fetch --unshallow`  turn the shallow clone into a full repo
3. `git remote set-branches origin '*'`  allow access to remote branches
4. `git fetch`  fetch the remote branches
5. `git checkout notebooks` change branch

**Comment by agstephens** [comment]
I think this was an intermittent problem.
