### ISSUE TITLE
Create procedures, and guidelines for presenters, about how we set up and use breakout rooms during the course

### ISSUE THREAD

**Issue by agstephens** [ncasuk/ncas-isc#75]
We are proposing that the main Zoom meeting will be running whenever we are not in breaks.

We will offer people the chance to sit at _tables_ (i.e. breakout rooms), and we need rules of engagement for:

- wanting to be in a room with specific people 
- wanting to not be in a room with specific people
- not wanting to be in a room at all
- wanting to transfer to another room
- other stuff.

**Comment by japamment** [comment]
We now have course "Terms of engagement" document: https://docs.google.com/document/d/1XMW6WmyNcWgBv616U-tmGyRafCdaV90W55xPhAV3aDI/edit.
