### ISSUE TITLE
dict.items loop example

### ISSUE THREAD

**Issue by alaniwi** [ncasuk/ncas-isc#9]
In last slide of
https://github.com/ncasuk/ncas-isc/blob/master/python/presentations/learning_python/19_ceda-dict.ppt

we could do with an example of looping over the return value of the `items` method. (It should be familiar to students because they have already encountered `for (i, val) in enumerate(....)` by this point, but might help as a reminder.)

**Comment by alaniwi** [comment]
(Sorry, no easy access to MS Office or would do it myself...)

**Comment by agstephens** [comment]
Fixed.
